FROM node:alpine
WORKDIR /app/frontend
COPY . .
RUN npm install
CMD ["npm", "run", "serve"]

# Deloy server
# build stage
# FROM node:13-alpine as build-stage
# WORKDIR /app/frontend
# COPY . .
# RUN npm install
# RUN npm run build

# # production stage
# FROM nginx:1.17-alpine as production-stage
# COPY --from=build-stage /app/frontend/build /usr/share/nginx/html
# CMD ["nginx", "-g", "daemon off;"]